server:
  port: 8761

spring:
  cloud:
    config:
      import-check:
        enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
