server:
  port: 8761

spring:
  cloud:
    config:
      import-check:
        enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 3000

management:
  endpoints:
    web:
      exposure:
        include: "*"
